-- Basics --

-- this is a comment
-- a rule is a sequence of *atoms*:

play-card E
it E Card
~ move Card play-area

-- an atom is a sequence of terms or variables. terms are lower-case, variables uppercase or start with `_`. `_` alone is the blank
-- atoms are separated by newlines or `,`. the previous is equivalently:

play-card E, it E Card, ~ move Card play-area

-- rules represent relational queries against a db store
-- each atom is a pattern
-- like the current implementation, each stored tuple has time information attached
-- unlike the current implementation, this time info is now a pair of terms representing start and end points in time
-- an *interval* is a pair (l, t) of values called *moments*.
-- the database stores both tuples (each having an interval) and moment ordering facts (statements that m1 < m2)

-- queries match only tuples that *overlap*:
--   (l1, r1) overlaps (l2, r2) iff l1 <= r2 and l2 <= r1
-- we further require that l1 and l2 are comparable (either l1 < l2 or l2 < l1 is in the database) as are r1/r2
-- so, `a, b` succeeds for each pair of tuples `a` and `b` such that their intervals overlap and their endpoints are comparable
-- evaluation proceeds one atom at a time; there is a time interval `(l, r)` called the *anchor* as part of the eval context
--   the anchor is initially (bot, top) (bot indicates a minimal moment that is less than every other; top is respectively maximal); this interval overlaps all other ones
-- after each atom `a`, if the interval `(al, ar)` of `a` overlaps `(l, r)`, then anchor is replaced by (max al l, min ar r).
--   note that, since we require comparable endpoints, this interval is a well-defined pair of moments

-- there are several ways for a rule to assert a new tuple, each of which also asserts temporal info about its interval:
--   `~`: the new atom interval `(l', r')` is fresh-generated and strictly contained within the anchor
--   `+`: the new atom interval `(l', top)` has fresh left endpoint and right endpoint equal to top
--     for anchor (l, r), assert l < l' < r
--   `^`: the new atom interval is exactly the current anchor
--   `!`: the new atom is marked as an *output* tuple; it is stored apart from other tuples, doesn't have an interval, cannot match atom patterns
-- fresh moment values are constructed analogously to the interval id values currently constructed: they contain a lexical part (the rule name and location in the rule) and a dynamic part (the variables bound by the query so far)
-- in any case, execution proceeds with an updated anchor: in the case of `~` for example, since the new interval is strictly smaller, it becomes the new anchor

-- terminology:
--   - a tuple created by `~` is called an *episode*
--   - a tuple created by `+` is called a *fact*
--   - a tuple created by `^` may be either, depending on the anchor at the point it's created
--   - a tuple created by `!` is called an *output* or *external tuple*

-- Subqueries ( ... ) --

-- actually, evaluation requires a stack of anchors
-- these are used to handle sub-queries which temporarily modify the anchor.
-- here is an annotated example:

activate A
it A call-to-guard
target A T

  -- rule contains a parenthesized sub-rule
  -- entering:
  --   current anchor is A
  --   push a copy of A onto a stack
  --   inside continues normally
  ( ~ gather G
    it G X
    to G To
    ! dahan X
    + is To T )
  -- exiting: pop current anchor
  -- current anchor is now A again

  ( at D T
    dahan D
    ~ defend D1
    it D1 I
    amount D1 A
    + is I T
    + is A 1 )

-- Expanding queries with assertion --

-- like the current implementation, when an assertion statement is followed by a match,
-- we generate multiple rules:

p1 X
~ p2 X
p3 Y
~ p4 Y

-- becomes two rules:

p1 X
~ [Id-left, Id-right] p2 X

p1 X
[Id-left, Id-right] p2 X
p3 Y
~ p4 Y

-- we still need an IR with terms representing interval endpoint values as indicated above using `[Id-left, Id-right]`
-- why: second rule should *only* match `p2 X` tuples that were generated by the preceding rule
-- the lexical info in the fresh-moment terms ensures uniqueness
-- motivation for this feature: it allows the rule to see `p3`, which might be asserted by a different rule in response to the new `p2`.
--   that is, it allows information passing between different rules without the need to manually split the rule
--   in a sense, we are yielding control to other rules after each assertion

-- we apply this to `~`, `+` and `^` atoms but not `!` (nothing can match them, so there is no need to yield control)

-- note that sibling `~` atoms end up nested: `~a, ~b, ~c` creates three nested episodes

-- Scoping --

-- variables are in scope from the "time" they are first bound until the end of the rule

episode E, ( some-property E P )
+ property-reference P

-- Interval Order --
-- we define that (l, r) comes before (l', r') if r <= l'
-- this is a partial order

-- Aggregation --

-- there is another atom syntax: an atom may end with `-> <term>`, e.g. `foo -> 2` or `foo X Y -> (f Z)`
-- these are called *weighted*
-- a weighted atom assertion behaves like a normal assertion: `foo -> 2` can be stored just like `foo 2`
-- a weighted atom query however performs an aggregation at the point it occurs
-- every db atom that matches the pattern and *contains* the current anchor is included.
--   an interval (l, r) contains (l', r') if l <= l' and r' <= r
-- the weights are then aggregated according to an aggregation function that is declared separately for the relation
--   allowed functions:
--     sum
--       adds all weights
--     count
--       counts number of tuples
--     last
--       takes the weight from the last atom (by interval order)
--       if multiple "last" atoms, this aggregation is multi-valued
-- suppose we declare

% points -> sum

-- with the rule

+ points -> 3
+ points -> 4
+ bar
points -> N

-- then N ends up bound to 7, because we have two tuples `[t1, top] points -> 3` and `[t2, top] points -> 4` and `[t3, t4] bar`
--   with t1 < t2 < t3, current anchor (t3, t4), so both points tuples contain `(t3, t4)`

-- empty reductions:
-- each aggregate function will optionally have a zero value (count, sum)
--   so, a count or sum pattern always succeeds
-- without one, an empty reduction fails (last)

-- Sequencing --

-- finally, we introduce a syntax `);` for temporal sequencing:

foo
  ( ~ e1 );
  ~e2

-- this rule creates two sub-episodes e1 and e2 of foo.
-- the `);` behaves like `)` in that it pops the top anchor from the stack;
--   however, instead of continuing with the existing anchor that is now top of stack, we first modify it by replacing its left endpoint with the *right* endpoint of the interval just popped.
-- the following annotations show the anchor state at each point of the rule:

-- [(bot, top)]
foo
-- [(foo_l, foo_r)]
(
-- [(foo_l, foo_r), (foo_l, foo_r)]
~ e1
-- [(foo_l, foo_r), (e1_l, e1_r)]
);
-- [(e1_r, foo_r)]
~e2
-- [(e2_l, e2_r)]

-- this doesn't show the moment assertions that are produced as we handle `~e1` and `~e2`;
-- in particular, the key point is that evaluation asserts e1_r < e2_l; that is, e1 comes before e2 in the interval order
